String teachername = "Tess Løvgreen";
int antalDage = 365;
String by = "København";
boolean random = true;
int math = 60*24;
float tal = 22.12
String tekst = "Hej, jeg heddder "+teachername;
boolean random2 = false;
float math2 = 2.2 + 33;
char bogstav = 'S';